
CREATE TABLE CUSTOMERS(
CUSTOMER_ID VARCHAR2(15) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(15) NOT NULL,
CONTACT_NAME VARCHAR2(15) UNIQUE,
ADDRESS VARCHAR2(15) NOT NULL,
CITY VARCHAR2(15) NOT NULL,
POSTAL_CODE VARCHAR2(15) NOT NULL,
COUNTRY VARCHAR2(15) NOT NULL
);

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID VARCHAR2 (15) PRIMARY KEY,
BIRTH_DATE  VARCHAR2 (15),
PHOTO       VARCHAR2 (15) NOT NULL,
NOTES       VARCHAR2 (15),
NAME        VARCHAR2 (15) NOT NULL,
MANAGER     VARCHAR2 (15)
);


CREATE TABLE SHIPPERS(
SHIPPER_ID VARCHAR2(15) PRIMARY KEY,
SHIPPER_NAME VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL
);

CREATE TABLE ORDERS(
ORDER_ID NUMBER PRIMARY KEY,
CUSTOMER_ID VARCHAR2(15) NOT NULL,
EMPLOYEE_ID VARCHAR2(15) NOT NULL,
ORDER_DATE DATE DEFAULT SYSDATE,
SHIPPER_ID VARCHAR2(15) NOT NULL,
CONSTRAINT ORDERS_FK_CUSTOMERS FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID),
CONSTRAINT ORDERS_FK_EMPLOYEES FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID),
CONSTRAINT ORDERS_FK_SHIPPERS FOREIGN KEY(SHIPPER_ID)
REFERENCES SHIPPERS(SHIPPER_ID)
);
--------------------------------------------------------------------------------
CREATE TABLE SUPPLIERS(
SUPPLIER_ID VARCHAR2(15) PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(15) NOT NULL,
CONTACT_NAME VARCHAR2(15) UNIQUE,
ADDRESS VARCHAR2(15) NOT NULL,
CITY VARCHAR2(15) NOT NULL,
POSTAL_CODE VARCHAR2(15) NOT NULL,
COUNTRY VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE CATEGORY_ID
START WITH 1000
INCREMENT BY 1;

CREATE TABLE CATEGORIES(
CATEGORY_ID NUMBER PRIMARY KEY,
CATEGORY_NAME VARCHAR2(15) NOT NULL,
DESCRIPTION VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE PRODUCT_ID
START WITH 1000
INCREMENT BY 1;

CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(15) NOT NULL,
SUPPLIER_ID VARCHAR2(15) NOT NULL,
CATEGORY_ID NUMBER NOT NULL,
UNIT VARCHAR2(15),
PRICE NUMBER,
CONSTRAINT PRODUCTS_FK_SUPPLIERS FOREIGN KEY(SUPPLIER_ID) 
REFERENCES SUPPLIERS(SUPPLIER_ID),
CONSTRAINT PRODUCTS_FK_CATEGORIES FOREIGN KEY(CATEGORY_ID) 
REFERENCES CATEGORIES(CATEGORY_ID)
);
--------------------------------------------------------------------------------
CREATE SEQUENCE ORDER_DETAIL_ID
START WITH 1000
INCREMENT BY 1;

CREATE TABLE ORDER_DETAILS(
ORDER_DETAIL_ID NUMBER PRIMARY KEY,
ORDER_ID NUMBER NOT NULL,
PRODUCT_ID NUMBER NOT NULL,
QUANTITY NUMBER,
CONSTRAINT ORDER_DETAILS_FK_PRODUCTS FOREIGN KEY(PRODUCT_ID)
REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT ORDER_DETAILS_FK_ORDERS FOREIGN KEY(ORDER_ID)
REFERENCES ORDERS(ORDER_ID)
);

-- 실행
SELECT * FROM TAB;

-- TEST
DROP TABLE PRODUCTS;

ALTER TABLE TEST
ADD TEST2 VARCHAR2(10);

ALTER TABLE TEST
DROP COLUMN TEST2;

ALTER TABLE MEMBER
ADD PRIMARY KEY(ID);


INSERT INTO ORDER_DETAILS(ART_SEQ, TITLE, CONTENT, REGDATE, ID)
VALUES(ART_SEQ.NEXTVAL,'지우보라','메롱',SYSDATE,'hong');
