SELECT * FROM CUSTOMERS;

--1단계 현재 목록에서 ROWNUM 을 추가한다.
SELECT ROWNUM "NO.", C.*
FROM CUSTOMERS C
WHERE ROWNUM BETWEEN 1 AND 5;

--2단계 ROWNUM 을 역순으로 정렬한다.
SELECT ROWNUM RNUM, C.*
FROM CUSTOMERS C
ORDER BY RNUM DESC;

--3단계 페이지사이즈(5) 만큼만 출력한다.
SELECT *
        FROM (SELECT ROWNUM RNUM, C.*
                FROM CUSTOMERS C
                ORDER BY RNUM DESC)
WHERE RNUM BETWEEN 1 AND 28;

SELECT T2.*
FROM (SELECT ROWNUM R2, T.*
        FROM (SELECT ROWNUM RNUM, C.*
                FROM CUSTOMERS C
                ORDER BY RNUM DESC) T) T2
WHERE R2 BETWEEN 1 AND 5;

SELECT COUNT(*) FROM CUSTOMERS;